# Generated by Django 4.0.2 on 2022-02-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviyel_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
