# Generated by Django 4.0.2 on 2022-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviyel_api', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('speaker', 'Speaker')], default='participant', max_length=200),
        ),
    ]
