# Generated by Django 4.0.2 on 2022-02-28 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviyel_api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
