# Generated by Django 4.0.2 on 2022-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviyel_api', '0004_alter_conference_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
